Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -48,6 +48,13 @@ jobs:
 
     - name: List all cruuent files and directories
       run: ls -R
+
+    - name: Check file existence
+      run: |
+        if [ ! -f "${{ github.workspace }}/edgetts.exe" ]; then
+          echo "File not found: edgetts.exe"
+          exit 1
+        fi
       
     - name: Set date variable
       run: |
@@ -59,4 +66,4 @@ jobs:
       uses: actions/upload-artifact@v4
       with:
         name: ${{ env.ARTIFACT_NAME }}
-        path: ${{ github.workspace }}\edgetts.exe
+        path: ${{ github.workspace }}/edgetts.exe
